MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7

# for ScaledAdam optimizer
TRAIN:
  BASE_LR: 0.025
  WARMUP_EPOCHS: 2
  EPOCHS: 100
  OPTIMIZER:
    BETAS: (0.9, 0.999)
    PARAM_MIN_RMS: 1.0e-5
    PARAM_MAX_RMS: 3.0
