MODEL:
  TYPE: swin4
  NAME: swin_tiny_patch4_window7_224_share_attn_new_dim
  DROP_PATH_RATE: 0.2
  SWIN4:
    EMBED_DIMS: [ 64, 128, 256, 512 ]
    DEPTHS: [ 2, 2, 4, 2 ]
    NUM_HEADS: [ 2, 4, 8, 16 ]
    QUERY_HEAD_DIMS: [ 32, 32, 32, 32 ]
    VALUE_HEAD_DIMS: [ 32, 32, 32, 32 ]
    WINDOW_SIZE: 7
    MLP_RATIO: 2.

      # # for ScaledAdam optimizer
      # TRAIN:
      #   BASE_LR: 0.03
      #   LR_BATCHES: 7500
      #   LR_EPOCHES: 30
      #   CLIP_GRAD: None
